// Placeholder Firebase options file.
//
// This file is normally generated by `flutterfire configure`. Until you run
// that command with your real Firebase project, [DefaultFirebaseOptions]
// returns `null` and the app skips Firebase initialization (see [main.dart]).
//
// To wire up real Firebase:
//   1. Install the FlutterFire CLI: `dart pub global activate flutterfire_cli`
//   2. Run: `flutterfire configure --project=<your-firebase-project-id>`
//   3. Replace this file with the generated one.

import 'package:firebase_core/firebase_core.dart';

/// Default Firebase options for the current platform.
///
/// Returns `null` until real options are generated, signalling the app to
/// skip [Firebase.initializeApp].
abstract final class DefaultFirebaseOptions {
  static FirebaseOptions? get currentPlatform => null;
}
